### ISSUE TITLE
Add a link to this repo to @jsf-clabot profile page.

### ISSUE THREAD

**Issue by ChALkeR** [JSFoundation/cla-assistant#11]
@jsf-clabot has no contact information, it took time for me to locate this repo to report #10.
I suggest adding the link to this repo to @jsf-clabot profile, instead of a generic link to https://js.foundation.

Also, I believe you should add a link from https://cla.js.foundation to here. Again — it took me time to find this repo.

**Comment by JSFOwner** [comment]
Link added to bot's bio

**Comment by ChALkeR** [comment]
@JSFOwner Thanks!
